name: Periodic Health Check

on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  health_check:
    runs-on: ubuntu-latest
    steps:
      - name: Perform Health Check
        uses: jtalk/url-health-check-action@v4
        with:
          url: 'http://localhost:5000/'